apiVersion: v1
kind: Secret
type: Opaque
data:
  {{- $couchdb_user := .Values.user }}
  {{- $couchdb_password := .Values.password }}
  user: {{ $couchdb_user | b64enc | quote}}
  password: {{ $couchdb_password | b64enc | quote }}
  binding: {{ cat `{"username":"` $couchdb_user `","password":"` $couchdb_password `","host":"` .Release.Name `-` .Values.service.name `","port":` .Values.service.externalPort `,"url":"http://` $couchdb_user `:` $couchdb_password `@` .Release.Name `-` .Values.service.name `:` .Values.service.externalPort `"}` | nospace | b64enc | quote }}
metadata:
  name: {{ .Values.binding.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
