apiVersion: v1
data:
  key: {{ .Values.hs256key.secret | b64enc }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: bluecompute
    tier: backend
    micro: auth
  name: "{{ .Release.Name }}-{{ .Values.hs256key.secretName }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
