# Default values for micro-orders.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-orders
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: icpregistry

hs256key:
  skipDelete: true
  secretName: bluecompute-hs256key
  secret: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 128Mi

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

service:
  name: orders
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

ingress:
  enabled: false
  loadBalancerID: ENTER_PRIVATE_LOAD_BALANCER_ID

tls:
  enabled: false
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

mysql:
  binding:
    name: binding-ordersdb-mysql

messagehub:
  binding:
    name:
