apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    release: {{.Release.Name | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: bluecompute
    micro: orders
    tier: backend
