apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.clustername }}-elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
    release: {{.Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ toYaml .Values.labels | indent 8 }}
    spec:
      volumes:
        {{ template "elasticsearchDataVolume" . }}
      containers:
      - name: elasticsearch
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: KUBERNETES_CA_CERTIFICATE_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: "CLUSTER_NAME"
            value: "{{ .Values.clustername }}"
          - name: "DISCOVERY_SERVICE"
            value: "{{ .Release.Name }}-{{ .Values.service.name }}"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_DATA
            value: "true"
          - name: HTTP_ENABLE
            value: "true"
          - name: "ES_JAVA_OPTS"
            value: "-Xms256m -Xmx256m"
        volumeMounts:
          - mountPath: /data
            name: storage
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP

